# Generated by Django 2.2.2 on 2019-07-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_convnetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='convnetmodel',
            name='name',
            field=models.CharField(default="What's that conv", max_length=20),
        ),
    ]
